baseURL = "https://nabilkara.github.io/"
languageCode = "en-us"
title = "Nabil Kara — CTF Writeups"
theme = "poison"
pluralizelisttitles = false

[pagination]
  pagerSize = 10

[params]
  brand = "Nabil Kara"                        
  brand_image = "/images/logo.png"        
  description = """Hi I'm Nabil a cyber security student at USTHB , Algeria ,  and a CTF player at TroJeun , with strong intrest in cryptography , OSINT
  and Web exploitation"""              
  dark_mode = true

  front_page_content = ["posts"]

  # Sidebar navigation menu
  menu = [
  { Name = "Posts", URL = "/posts/", HasChildren = true, Limit = 5 },
  ]


  # Social links
  github_url = "https://github.com/NabilKara"
  discord_url = "https://discord.com/users/1023863221549006938"
  email_url = "mailto:karanabil420@gmail.com"
  linkedin_url = "https://www.linkedin.com/in/nabil-kara-42b1211aa/"
  x_url = "https://x.com/NabilKara12312"

  rss_icon = true
  rss_section = "posts"

  moon_sun_background_color = "#515151"
  moon_sun_color = "#FFF"
  sidebar_a_color = "#FFF"
  sidebar_bg_color = "#202020"
  sidebar_h1_color = "#FFF"
  sidebar_img_border_color = "#515151"
  sidebar_p_color = "#909090"
  sidebar_socials_color = "#FFF"

  code_color = "#000"
  code_background_color = "#E5E5E5"
  code_block_color = "#FFF"
  code_block_background_color = "#272822"
  content_bg_color = "#FAF9F6"
  date_color = "#515151"
  link_color = "#268BD2"
  list_color = "#5A5A5A"
  post_title_color = "#303030"
  table_border_color = "#E5E5E5"
  table_stripe_color = "#F9F9F9"
  text_color = "#222"

  code_color_dark = "#FFF"
  code_background_color_dark = "#515151"
  code_block_color_dark = "#FFF"
  code_block_background_color_dark = "#272822"
  content_bg_color_dark = "#121212"
  date_color_dark = "#9A9A9A"
  link_color_dark = "#268BD2"
  list_color_dark = "#9D9D9D"
  post_title_color_dark = "#DBE2E9"
  table_border_color_dark = "#515151"
  table_stripe_color_dark = "#202020"
  text_color_dark = "#EEE"

[taxonomies]
  series = "series"
  tags = "tags"

[languages]
  [languages.en]
    languageName = "English"
    weight = 1
    [languages.en.params]
      Author = { name = "Nabil Kara" }
[caches]
  [caches.images]
    dir = ':cacheDir/images'